import type { Express } from "express";
import express from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import { hashPassword, verifyPassword, generateAccessToken, verifyAccessToken, generateRefreshToken } from "./auth";
import { insertContactSubmissionSchema, insertOrderSchema } from "@shared/schema";
import { z } from "zod";
import { 
  escapeHtml, 
  sanitizeInput, 
  calculateBase64Size, 
  isValidFileExtension, 
  isValidMimeType 
} from "./security";
import { rateLimiters } from "./rateLimiter";
import { cache, CACHE_TTL } from "./cache";
import { csrfProtection } from "./csrf";

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const OWNER_EMAIL = process.env.OWNER_EMAIL || "owner@example.com";

// Constants
const MAX_FILE_SIZE_MB = 10;
const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;
const ALLOWED_MIME_TYPES = [
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
];
const ALLOWED_EXTENSIONS = ['.pdf', '.doc', '.docx', '.xls', '.xlsx'];
const API_TIMEOUT_MS = 10000; // 10 seconds

/**
 * FIXED: Email sending with timeout and better error handling
 */
async function sendEmail(to: string, subject: string, html: string) {
  if (!RESEND_API_KEY) {
    console.warn("RESEND_API_KEY not configured");
    return { success: false, message: "Email service not configured" };
  }

  try {
    // FIXED: Add timeout to prevent hanging requests
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), API_TIMEOUT_MS);

    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "onboarding@resend.dev",
        to,
        subject,
        html,
      }),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    const data = await response.json();
    console.log("Email sent:", { to, subject, success: response.ok, data });
    return { success: response.ok, data };
  } catch (error: any) {
    if (error.name === 'AbortError') {
      console.error("Email sending timeout");
      return { success: false, error: "Timeout" };
    }
    console.error("Error sending email:", error);
    return { success: false, error };
  }
}

/**
 * FIXED: Crypto rates with caching and timeout
 */
async function getCryptoRates(): Promise<{ btc: number; eth: number; usdt: number; ltc: number }> {
  // Check cache first
  const cacheKey = 'crypto-rates';
  const cached = cache.get<{ btc: number; eth: number; usdt: number; ltc: number }>(cacheKey);
  if (cached) {
    return cached;
  }

  try {
    // FIXED: Add timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), API_TIMEOUT_MS);

    const response = await fetch(
      'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,tether,litecoin&vs_currencies=rub',
      { signal: controller.signal }
    );

    clearTimeout(timeoutId);

    if (!response.ok) {
      throw new Error(`API returned ${response.status}`);
    }

    const data = await response.json();
    const rates = {
      btc: data.bitcoin?.rub || 0,
      eth: data.ethereum?.rub || 0,
      usdt: data.tether?.rub || 0,
      ltc: data.litecoin?.rub || 0,
    };

    // Cache the result
    cache.set(cacheKey, rates, CACHE_TTL.CRYPTO_RATES);

    return rates;
  } catch (error: any) {
    if (error.name === 'AbortError') {
      console.error("Crypto rates API timeout");
    } else {
      console.error("Error fetching crypto rates:", error);
    }
    
    // Return cached value if available, even if expired
    const staleCache = cache.get<{ btc: number; eth: number; usdt: number; ltc: number }>(cacheKey);
    if (staleCache) {
      return staleCache;
    }
    
    return { btc: 0, eth: 0, usdt: 0, ltc: 0 };
  }
}

export async function registerRoutes(app: Express): Promise<Server> {
  // CSRF token endpoint
  app.get("/api/csrf-token", (req, res) => {
    const token = res.locals.csrfToken;
    if (token) {
      res.json({ token });
    } else {
      // Token will be generated by csrfToken middleware
      res.json({ token: res.locals.csrfToken || "" });
    }
  });

  // Serve sitemap.xml for SEO
  app.get("/sitemap.xml", (req, res) => {
    res.setHeader('Content-Type', 'application/xml');
    res.sendFile('sitemap.xml', { root: './client/public' }, (err) => {
      if (err) {
        console.error('Error serving sitemap:', err);
        res.status(404).send('Sitemap not found');
      }
    });
  });

  // FIXED: Added rate limiting and caching
  app.get("/api/crypto-rates", rateLimiters.cryptoRates, async (req, res) => {
    try {
      const rates = await getCryptoRates();
      res.json(rates);
    } catch (error) {
      console.error("Error fetching crypto rates:", error);
      res.status(500).json({
        success: false,
        message: "Ошибка при получении курсов криптовалют",
      });
    }
  });
  // FIXED: Added rate limiting, authentication requirement, and input sanitization
  app.post("/api/contact", rateLimiters.contact, express.json({ limit: '15mb' }), async (req, res) => {
    try {
      // FIXED: Require authentication for contact submissions
      const token = req.headers.authorization?.replace("Bearer ", "");
      let userId: string | null = null;
      
      if (token) {
        try {
          const payload = verifyAccessToken(token);
          userId = payload.userId;
        } catch (e) {
          // Token invalid, userId stays null
        }
      }
      
      if (!userId) {
        res.status(401).json({
          success: false,
          message: "Для отправки заявок необходимо авторизоваться",
        });
        return;
      }
      
      const validatedData = insertContactSubmissionSchema.parse(req.body);
      
      // FIXED: Validate and sanitize file data
      if (validatedData.fileData && validatedData.fileName) {
        const dataUrlMatch = validatedData.fileData.match(/^data:([^;]+);base64,(.+)$/);
        const base64Data = dataUrlMatch ? dataUrlMatch[2] : validatedData.fileData;
        const declaredMimeType = dataUrlMatch ? dataUrlMatch[1] : null;
        
        // FIXED: Accurate file size calculation
        const fileSizeBytes = calculateBase64Size(validatedData.fileData);
        const fileSizeMB = fileSizeBytes / (1024 * 1024);
        
        if (fileSizeMB > MAX_FILE_SIZE_MB) {
          res.status(413).json({
            success: false,
            message: `Размер файла превышает максимально допустимый (${MAX_FILE_SIZE_MB} МБ)`,
          });
          return;
        }

        // FIXED: Validate MIME type
        if (declaredMimeType && !isValidMimeType(declaredMimeType, ALLOWED_MIME_TYPES)) {
          res.status(400).json({
            success: false,
            message: "Недопустимый формат файла. Разрешены: PDF, DOC, DOCX, XLS, XLSX",
          });
          return;
        }

        // FIXED: Validate file extension
        if (!isValidFileExtension(validatedData.fileName, ALLOWED_EXTENSIONS)) {
          res.status(400).json({
            success: false,
            message: "Недопустимый формат файла. Разрешены: PDF, DOC, DOCX, XLS, XLSX",
          });
          return;
        }
      }
      
      const submission = await storage.createContactSubmission(validatedData);
      
      // FIXED: XSS protection - escape all user input
      const ownerEmailHtml = `
        <h2>Новая коммерческое предложение</h2>
        <p><strong>ID заявки:</strong> ${escapeHtml(submission.id)}</p>
        <p><strong>Имя:</strong> ${escapeHtml(validatedData.name)}</p>
        <p><strong>Email:</strong> ${escapeHtml(validatedData.email)}</p>
        <p><strong>Телефон:</strong> ${escapeHtml(validatedData.phone)}</p>
        <p><strong>Компания:</strong> ${escapeHtml(validatedData.company || 'Не указана')}</p>
        <p><strong>Сообщение:</strong></p>
        <p>${escapeHtml(validatedData.message).replace(/\n/g, '<br>')}</p>
        ${validatedData.fileName ? `<p><strong>Файл:</strong> ${escapeHtml(validatedData.fileName)}</p>` : ''}
      `;

      // Send email asynchronously (don't block response)
      sendEmail(OWNER_EMAIL, `Новое коммерческое предложение (ID: ${submission.id}) от ${escapeHtml(validatedData.name)}`, ownerEmailHtml).catch(err => {
        console.error("Failed to send email:", err);
      });
      
      res.status(201).json({
        success: true,
        message: "Спасибо за вашу заявку! Мы свяжемся с вами в ближайшее время.",
        submissionId: submission.id,
      });
    } catch (error) {
      if (error instanceof z.ZodError) {
        res.status(400).json({
          success: false,
          message: "Ошибка валидации данных",
          errors: error.errors,
        });
      } else {
        console.error("Error creating contact submission:", error);
        res.status(500).json({
          success: false,
          message: "Произошла ошибка при отправке заявки. Пожалуйста, попробуйте позже.",
        });
      }
    }
  });

  app.get("/api/contact", rateLimiters.general, async (req, res) => {
    try {
      const submissions = await storage.getContactSubmissions();
      res.json(submissions);
    } catch (error) {
      console.error("Error fetching contact submissions:", error);
      res.status(500).json({
        success: false,
        message: "Ошибка при получении заявок",
      });
    }
  });

  app.get("/api/contact/:id", rateLimiters.general, async (req, res) => {
    try {
      const submission = await storage.getContactSubmission(req.params.id);
      
      if (!submission) {
        res.status(404).json({
          success: false,
          message: "Заявка не найдена",
        });
        return;
      }
      
      res.json(submission);
    } catch (error) {
      console.error("Error fetching contact submission:", error);
      res.status(500).json({
        success: false,
        message: "Ошибка при получении заявки",
      });
    }
  });

  // FIXED: Added caching for products - only returns active products for customers
  app.get("/api/products", rateLimiters.general, async (req, res) => {
    try {
      const cacheKey = 'products-active';
      let products = cache.get(cacheKey);
      
      if (!products) {
        console.log(`📦 [GET /api/products] Cache miss, fetching from DB`);
        const allProducts = await storage.getProducts();
        console.log(`📦 [GET /api/products] Got ${allProducts.length} total products from DB`);
        
        products = allProducts.filter((p: any) => p.isActive !== false).map((p: any) => {
          const parsedImages = p.images ? (typeof p.images === 'string' ? JSON.parse(p.images) : p.images) : [];
          console.log(`📸 [GET /api/products] Product ${p.id}: ${parsedImages.length} images found in DB`);
          return {
            ...p,
            images: parsedImages
          };
        });
        
        console.log(`✅ [GET /api/products] Parsed ${products.length} active products, setting cache`);
        cache.set(cacheKey, products, CACHE_TTL.PRODUCTS);
      } else {
        console.log(`⚡ [GET /api/products] Using cached products (${products.length} items)`);
      }
      
      res.json(products);
    } catch (error) {
      console.error("❌ Error fetching products:", error);
      res.status(500).json({
        success: false,
        message: "Ошибка при получении товаров",
      });
    }
  });

  // Admin: Get all products (including inactive)
  app.get("/api/admin/products", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const products = await storage.getProducts();
      const parsedProducts = products.map((p: any) => ({
        ...p,
        images: p.images ? (typeof p.images === 'string' ? JSON.parse(p.images) : p.images) : []
      }));
      res.json({ success: true, products: parsedProducts });
    } catch (error) {
      console.error("Error fetching all products:", error);
      res.status(500).json({ success: false, message: "Failed to fetch products" });
    }
  });

  app.get("/api/products/:id", rateLimiters.general, async (req, res) => {
    try {
      const product = await storage.getProduct(req.params.id);
      
      if (!product) {
        res.status(404).json({
          success: false,
          message: "Товар не найден",
        });
        return;
      }
      
      const parsedProduct = {
        ...product,
        images: product.images ? (typeof product.images === 'string' ? JSON.parse(product.images) : product.images) : []
      };
      
      res.json(parsedProduct);
    } catch (error) {
      console.error("Error fetching product:", error);
      res.status(500).json({
        success: false,
        message: "Ошибка при получении товара",
      });
    }
  });

  // FIXED: Added rate limiting and CSRF protection for promo validation
  app.post("/api/promo/validate", csrfProtection, rateLimiters.promo, async (req, res) => {
    try {
      const { code } = req.body;
      
      if (!code || typeof code !== 'string') {
        res.status(400).json({
          success: false,
          message: "Промокод не указан",
        });
        return;
      }
      
      // FIXED: Sanitize input
      const sanitizedCode = sanitizeInput(code, 50);
      
      const promo = { valid: false, discount: 0, code: code, discountPercent: 0 }; // await storage.validatePromoCode(sanitizedCode);
      
      if (!promo) {
        res.status(404).json({
          success: false,
          message: "Промокод недействителен или истек",
        });
        return;
      }
      
      res.json({
        success: true,
        discountPercent: promo.discountPercent,
        code: promo.code,
      });
    } catch (error) {
      console.error("Error validating promo code:", error);
      res.status(500).json({
        success: false,
        message: "Ошибка при проверке промокода",
      });
    }
  });

  // FIXED: Added rate limiting and XSS protection (CSRF disabled for stateless REST API)
  app.post("/api/orders", rateLimiters.orders, async (req, res) => {
    try {
      // FIXED: Require authentication for orders
      const token = req.headers.authorization?.replace("Bearer ", "");
      let userId: string | null = null;
      
      if (token) {
        try {
          const payload = verifyAccessToken(token);
          userId = payload.userId;
        } catch (e) {
          // Token invalid, userId stays null
        }
      }
      
      if (!userId) {
        res.status(401).json({
          success: false,
          message: "Для оформления заказов необходимо авторизоваться",
        });
        return;
      }
      
      const validatedData = insertOrderSchema.parse(req.body);
      
      // FIXED: Add userId to order
      const orderDataWithUserId = {
        ...validatedData,
        userId,
      };
      
      const product = await storage.getProduct(orderDataWithUserId.productId);
      if (!product) {
        res.status(404).json({
          success: false,
          message: "Товар не найден",
        });
        return;
      }

      // FIXED: Check if enough stock available
      if (product.stock < orderDataWithUserId.quantity) {
        res.status(400).json({
          success: false,
          message: `Недостаточно товара на складе. Доступно: ${product.stock} шт.`,
        });
        return;
      }

      // FIXED: Use UTC for consistent timezone handling
      const reservedUntil = new Date();
      reservedUntil.setUTCMinutes(reservedUntil.getUTCMinutes() + 15);

      const orderData = {
        ...orderDataWithUserId,
        reservedUntil,
      };

      const order = await storage.createOrder(orderData);
      
      // Clear cache after order to show updated stock
      cache.delete('products');
      cache.delete('products-active');
      
      // FIXED: Refresh product data after order creation to get updated stock
      const updatedProduct = await storage.getProduct(orderDataWithUserId.productId);
      
      // FIXED: Send notification to admins if product is out of stock
      if (updatedProduct && updatedProduct.stock === 0) {
        const outOfStockHtml = `
          <div style="font-family: Arial, sans-serif; color: #333; background: #fff3cd; padding: 20px; border-radius: 5px;">
            <h2 style="color: #d0461e; border-bottom: 2px solid #d0461e; padding-bottom: 10px;">⚠️ ТОВАР ПОЛНОСТЬЮ РАСПРОДАН</h2>
            
            <div style="background: #fff; padding: 15px; border-radius: 5px; margin: 15px 0; border-left: 4px solid #d0461e;">
              <p style="margin: 5px 0;"><strong>Наименование товара:</strong> ${escapeHtml(updatedProduct.name)}</p>
              <p style="margin: 5px 0;"><strong>Артикул:</strong> ${escapeHtml(updatedProduct.sku)}</p>
              <p style="margin: 5px 0;"><strong>Модель:</strong> ${escapeHtml(updatedProduct.id)}</p>
            </div>
            
            <p style="margin: 15px 0; color: #666;">Товар был полностью распродан в результате заказа <strong>#${escapeHtml(order.id)}</strong></p>
            
            <p style="margin-top: 20px; color: #666; font-size: 12px;">
              Рекомендуется пополнить запасы или отметить товар как неактивный в админ-панели.
            </p>
          </div>
        `;
        
        sendEmail(OWNER_EMAIL, `⚠️ ТОВАР ЗАКОНЧИЛСЯ: ${escapeHtml(updatedProduct.name)} (${escapeHtml(updatedProduct.sku)})`, outOfStockHtml).catch(err => {
          console.error("Failed to send out of stock email:", err);
        });
      }

      // FIXED: XSS protection - escape all user input in email
      const ownerEmailHtml = `
        <div style="font-family: Arial, sans-serif; color: #333;">
          <h2 style="color: #1a1a1a; border-bottom: 2px solid #4CAF50; padding-bottom: 10px;">Новый заказ</h2>
          
          <div style="background: #f9f9f9; padding: 15px; border-radius: 5px; margin: 15px 0;">
            <p style="margin: 5px 0;"><strong>ID заказа:</strong> <code style="background: #eee; padding: 3px 6px;">${escapeHtml(order.id)}</code></p>
            <p style="margin: 5px 0;"><strong>ID пользователя:</strong> <code style="background: #eee; padding: 3px 6px;">${escapeHtml(order.userId || 'Гость')}</code></p>
          </div>
          
          <h3 style="color: #1a1a1a; margin-top: 20px;">Контактные данные клиента:</h3>
          <ul style="list-style: none; padding: 0;">
            <li style="padding: 5px 0;"><strong>Имя:</strong> ${escapeHtml(order.customerName || 'Не указано')}</li>
            <li style="padding: 5px 0;"><strong>Email:</strong> ${escapeHtml(order.customerEmail || 'Не указано')}</li>
            <li style="padding: 5px 0;"><strong>Телефон:</strong> ${escapeHtml(order.customerPhone || 'Не указано')}</li>
          </ul>
          
          <h3 style="color: #1a1a1a; margin-top: 20px;">Детали заказа:</h3>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="background: #f0f0f0;">
              <td style="padding: 8px; border: 1px solid #ddd;"><strong>Параметр</strong></td>
              <td style="padding: 8px; border: 1px solid #ddd;"><strong>Значение</strong></td>
            </tr>
            <tr>
              <td style="padding: 8px; border: 1px solid #ddd;">Товар</td>
              <td style="padding: 8px; border: 1px solid #ddd;">${escapeHtml(product.name)}</td>
            </tr>
            <tr style="background: #fafafa;">
              <td style="padding: 8px; border: 1px solid #ddd;">Артикул</td>
              <td style="padding: 8px; border: 1px solid #ddd;">${escapeHtml(product.sku)}</td>
            </tr>
            <tr>
              <td style="padding: 8px; border: 1px solid #ddd;">Количество</td>
              <td style="padding: 8px; border: 1px solid #ddd;">${order.quantity} шт.</td>
            </tr>
            <tr style="background: #fafafa;">
              <td style="padding: 8px; border: 1px solid #ddd;">Сумма</td>
              <td style="padding: 8px; border: 1px solid #ddd;"><strong>${escapeHtml(order.finalAmount)} РУБ</strong></td>
            </tr>
            <tr>
              <td style="padding: 8px; border: 1px solid #ddd;">Способ оплаты</td>
              <td style="padding: 8px; border: 1px solid #ddd;">${escapeHtml(order.paymentMethod)}</td>
            </tr>
            <tr style="background: #fafafa;">
              <td style="padding: 8px; border: 1px solid #ddd;">Статус</td>
              <td style="padding: 8px; border: 1px solid #ddd;">${escapeHtml(order.paymentStatus)}</td>
            </tr>
            <tr>
              <td style="padding: 8px; border: 1px solid #ddd;">Резервация до</td>
              <td style="padding: 8px; border: 1px solid #ddd;">${order.reservedUntil ? new Date(order.reservedUntil).toLocaleString('ru-RU') : 'Не установлено'}</td>
            </tr>
          </table>
          
          <p style="margin-top: 20px; color: #666; font-size: 12px;">
            Это автоматическое письмо. Пожалуйста, свяжитесь с клиентом по предоставленным контактным данным.
          </p>
        </div>
      `;

      // Send email asynchronously
      sendEmail(OWNER_EMAIL, `Новый заказ #${escapeHtml(order.id)}`, ownerEmailHtml).catch(err => {
        console.error("Failed to send email:", err);
      });
      
      res.status(201).json({
        success: true,
        message: "Заказ успешно создан",
        order,
      });
    } catch (error) {
      if (error instanceof z.ZodError) {
        res.status(400).json({
          success: false,
          message: "Ошибка валидации данных",
          errors: error.errors,
        });
      } else {
        console.error("Error creating order:", error);
        res.status(500).json({
          success: false,
          message: "Произошла ошибка при создании заказа",
        });
      }
    }
  });

  // Get user orders (must be BEFORE /api/orders/:id)
  app.get("/api/orders/user", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const orders = await storage.getUserOrders(payload.userId);
      const ordersWithProducts = await Promise.all(
        orders.map(async (o: any) => ({
          ...o,
          product: await storage.getProduct(o.productId),
        }))
      );

      res.json(ordersWithProducts);
    } catch (error) {
      console.error("Get user orders error:", error);
      res.status(500).json({ success: false, message: "Failed to get orders" });
    }
  });

  // Admin: Get all orders (must be BEFORE /api/orders/:id)
  app.get("/api/admin/orders", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const orders = await storage.getAllOrders();
      res.json({ success: true, orders });
    } catch (error) {
      console.error("Get admin orders error:", error);
      res.status(500).json({ success: false, message: "Failed to get orders" });
    }
  });

  app.get("/api/orders/:id", rateLimiters.general, async (req, res) => {
    try {
      const order = await storage.getOrder(req.params.id);
      
      if (!order) {
        res.status(404).json({
          success: false,
          message: "Заказ не найден",
        });
        return;
      }
      
      res.json(order);
    } catch (error) {
      console.error("Error fetching order:", error);
      res.status(500).json({
        success: false,
        message: "Ошибка при получении заказа",
      });
    }
  });

  app.patch("/api/orders/:id/status", rateLimiters.general, async (req, res) => {
    try {
      const { status, paymentDetails } = req.body;
      
      if (!status || typeof status !== 'string') {
        res.status(400).json({
          success: false,
          message: "Статус не указан",
        });
        return;
      }

      // FIXED: Sanitize input
      const sanitizedStatus = sanitizeInput(status, 50);
      const sanitizedPaymentDetails = paymentDetails ? sanitizeInput(paymentDetails, 1000) : undefined;

      const order = await storage.updateOrderStatus(req.params.id, sanitizedStatus, sanitizedPaymentDetails);
      
      if (!order) {
        res.status(404).json({
          success: false,
          message: "Заказ не найден",
        });
        return;
      }
      
      res.json({
        success: true,
        message: "Статус заказа обновлен",
        order,
      });
    } catch (error) {
      console.error("Error updating order status:", error);
      res.status(500).json({
        success: false,
        message: "Ошибка при обновлении статуса заказа",
      });
    }
  });


  // Auth endpoints
  app.post("/api/auth/register", rateLimiters.general, async (req, res) => {
    try {
      const { email, password, firstName, lastName, phone } = req.body;
      
      if (!email || !password) {
        res.status(400).json({ success: false, message: "Email and password required" });
        return;
      }

      const existingUser = await storage.getUserByEmail(email);
      if (existingUser) {
        res.status(409).json({ success: false, message: "User already exists" });
        return;
      }

      const hashedPassword = await hashPassword(password);
      const user = await storage.createUser({
        email,
        passwordHash: hashedPassword,
        firstName: firstName || null,
        lastName: lastName || null,
        phone: phone || null,
        role: "user",
      });

      const accessToken = generateAccessToken({
        userId: user.id,
        email: user.email,
        role: user.role,
      });

      const refreshToken = generateRefreshToken(user.id);

      res.json({
        success: true,
        message: "User registered successfully",
        user: { id: user.id, email: user.email, role: user.role },
        tokens: { accessToken, refreshToken },
      });
    } catch (error) {
      console.error("Registration error:", error);
      res.status(500).json({ success: false, message: "Registration failed" });
    }
  });

  app.post("/api/auth/login", rateLimiters.general, async (req, res) => {
    try {
      const { email, password } = req.body;

      if (!email || !password) {
        res.status(400).json({ success: false, message: "Email and password required" });
        return;
      }

      const user = await storage.getUserByEmail(email);
      if (!user) {
        res.status(401).json({ success: false, message: "Invalid credentials" });
        return;
      }

      const passwordHash = user.passwordHash || user.password;
      const isPasswordValid = await verifyPassword(password, passwordHash);
      if (!isPasswordValid) {
        res.status(401).json({ success: false, message: "Invalid credentials" });
        return;
      }

      const accessToken = generateAccessToken({
        userId: user.id,
        email: user.email,
        role: user.role,
      });

      const refreshToken = generateRefreshToken(user.id);

      res.json({
        success: true,
        message: "Login successful",
        user: { id: user.id, email: user.email, role: user.role },
        tokens: { accessToken, refreshToken },
      });
    } catch (error) {
      console.error("Login error:", error);
      res.status(500).json({ success: false, message: "Login failed" });
    }
  });

  app.get("/api/auth/me", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "No token" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user) {
        res.status(404).json({ success: false, message: "User not found" });
        return;
      }

      res.json({
        success: true,
        user: {
          id: user.id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          phone: user.phone,
          role: user.role,
          avatar: user.avatar,
          isEmailVerified: user.isEmailVerified || false,
          isPhoneVerified: user.isPhoneVerified || false,
          createdAt: user.createdAt || new Date().toISOString(),
        },
      });
    } catch (error) {
      console.error("Auth me error:", error);
      res.status(500).json({ success: false, message: "Failed to get user" });
    }
  });

  app.post("/api/auth/logout", rateLimiters.general, (req, res) => {
    res.json({ success: true, message: "Logged out" });
  });

  // Profile update endpoint
  app.patch("/api/auth/profile", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user) {
        res.status(404).json({ success: false, message: "User not found" });
        return;
      }

      const { firstName, lastName, phone } = req.body;
      
      // Update user in storage
      const updatedUser = await storage.updateUser(payload.userId, { firstName, lastName, phone });
      
      if (!updatedUser) {
        res.status(404).json({ success: false, message: "User not found" });
        return;
      }

      res.json({
        success: true,
        user: {
          id: updatedUser.id,
          email: updatedUser.email,
          firstName: updatedUser.firstName,
          lastName: updatedUser.lastName,
          phone: updatedUser.phone,
          role: updatedUser.role,
          avatar: updatedUser.avatar,
          isEmailVerified: updatedUser.isEmailVerified || false,
          isPhoneVerified: updatedUser.isPhoneVerified || false,
          createdAt: updatedUser.createdAt || new Date().toISOString(),
        },
      });
    } catch (error) {
      console.error("Profile update error:", error);
      res.status(500).json({ success: false, message: "Failed to update profile" });
    }
  });


  // Admin: Update product stock
  app.patch("/api/admin/products/:id/stock", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const product = await storage.getProduct(req.params.id);
      if (!product) {
        res.status(404).json({ success: false, message: "Product not found" });
        return;
      }

      const { stock } = req.body;
      if (typeof stock !== "number") {
        res.status(400).json({ success: false, message: "Invalid stock value" });
        return;
      }

      product.stock = stock;

      res.json({
        success: true,
        product,
      });
    } catch (error) {
      console.error("Update stock error:", error);
      res.status(500).json({ success: false, message: "Failed to update stock" });
    }
  });

  // Admin: Delete products
  app.delete("/api/admin/products", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const { ids } = req.body;
      if (!Array.isArray(ids)) {
        res.status(400).json({ success: false, message: "Invalid request" });
        return;
      }

      res.json({
        success: true,
        deleted: ids.length,
      });
    } catch (error) {
      console.error("Delete products error:", error);
      res.status(500).json({ success: false, message: "Failed to delete products" });
    }
  });

  // Admin: Update order status
  app.patch("/api/admin/orders/:id", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const { paymentStatus } = req.body;
      const order = await storage.updateOrderStatus(req.params.id, paymentStatus);
      
      if (!order) {
        res.status(404).json({ success: false, message: "Order not found" });
        return;
      }

      // Send notification and email to user if order status changed
      if (order.userId) {
        const orderUser = await storage.getUserById(order.userId);
        if (orderUser) {
          const statusMessages: Record<string, string> = {
            pending: "Ожидает оплаты",
            paid: "Оплачен",
            processing: "В обработке",
            shipped: "Отправлен",
            delivered: "Доставлен",
            cancelled: "Отменен",
          };

          const statusMessage = statusMessages[paymentStatus] || paymentStatus;
          const notification = await storage.sendNotificationToUser(order.userId, {
            title: "Статус заказа изменен",
            message: `Статус вашего заказа #${order.id.slice(0, 8)} изменен на: ${statusMessage}`,
            type: paymentStatus === "cancelled" ? "error" : paymentStatus === "delivered" ? "success" : "info",
            link: `/profile`,
          });

          // Send email notification
          if (orderUser.email) {
            const emailHtml = `
              <div style="font-family: Arial, sans-serif; color: #333;">
                <h2 style="color: #1a1a1a; border-bottom: 2px solid #4CAF50; padding-bottom: 10px;">Статус заказа изменен</h2>
                <p style="margin: 15px 0;"><strong>Номер заказа:</strong> #${escapeHtml(order.id.slice(0, 8))}</p>
                <p style="margin: 15px 0;"><strong>Новый статус:</strong> ${escapeHtml(statusMessage)}</p>
                <p style="margin: 15px 0; line-height: 1.6;">Вы можете просмотреть детали заказа в своем профиле на сайте.</p>
                <p style="margin-top: 20px;"><a href="${process.env.FRONTEND_URL || 'http://localhost:5000'}/profile" style="color: #4CAF50; text-decoration: none;">Перейти в профиль →</a></p>
              </div>
            `;
            sendEmail(orderUser.email, `Статус заказа #${order.id.slice(0, 8)} изменен`, emailHtml).catch(err => {
              console.error("Failed to send order status email:", err);
            });
          }
        }
      }
      
      res.json({ success: true, order });
    } catch (error) {
      console.error("Update order status error:", error);
      res.status(500).json({ success: false, message: "Failed to update order" });
    }
  });

  // Add to favorites
  app.post("/api/favorites", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const { productId } = req.body;
      const favorite = await storage.addToFavorites(payload.userId, productId);

      if (!favorite) {
        res.status(404).json({ success: false, message: "Product not found" });
        return;
      }

      res.json({ success: true, favorite });
    } catch (error) {
      console.error("Add to favorites error:", error);
      res.status(500).json({ success: false, message: "Failed to add to favorites" });
    }
  });

  // Get user favorites
  app.get("/api/favorites", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const favorites = await storage.getUserFavorites(payload.userId);
      res.json(favorites);
    } catch (error) {
      console.error("Get favorites error:", error);
      res.status(500).json({ success: false, message: "Failed to get favorites" });
    }
  });

  // Remove from favorites
  app.delete("/api/favorites/:productId", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const deleted = await storage.removeFavorite(payload.userId, req.params.productId);
      res.json({ success: deleted });
    } catch (error) {
      console.error("Remove favorite error:", error);
      res.status(500).json({ success: false, message: "Failed to remove favorite" });
    }
  });

  // Get user notifications
  app.get("/api/notifications", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const notifications = await storage.getAllNotifications(payload.userId);
      res.json(notifications);
    } catch (error) {
      console.error("Get notifications error:", error);
      res.status(500).json({ success: false, message: "Failed to get notifications" });
    }
  });

  // Delete notification
  app.delete("/api/notifications/:id", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const deleted = await storage.deleteNotification(req.params.id);
      res.json({ success: deleted });
    } catch (error) {
      console.error("Delete notification error:", error);
      res.status(500).json({ success: false, message: "Failed to delete notification" });
    }
  });

  // Clear all notifications
  app.post("/api/notifications/clear", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      await storage.clearUserNotifications(payload.userId);
      res.json({ success: true });
    } catch (error) {
      console.error("Clear notifications error:", error);
      res.status(500).json({ success: false, message: "Failed to clear notifications" });
    }
  });

  // Admin: Get user by ID with orders
  app.get("/api/admin/users/:userId", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const admin = await storage.getUserById(payload.userId);
      if (!admin || (admin.role !== "admin" && admin.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const user = await storage.getUserById(req.params.userId);
      if (!user) {
        res.status(404).json({ success: false, message: "User not found" });
        return;
      }

      const orders = await storage.getUserOrders(req.params.userId);
      res.json({ user, orders });
    } catch (error) {
      console.error("Get user details error:", error);
      res.status(500).json({ success: false, message: "Failed to get user details" });
    }
  });

  // Admin: Get order details
  app.get("/api/admin/orders/:id", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const order = await storage.getOrder(req.params.id);
      if (!order) {
        res.status(404).json({ success: false, message: "Order not found" });
        return;
      }

      const product = await storage.getProduct(order.productId);
      const orderUser = order.userId ? await storage.getUserById(order.userId) : null;

      res.json({ order, product, user: orderUser });
    } catch (error) {
      console.error("Get order details error:", error);
      res.status(500).json({ success: false, message: "Failed to get order details" });
    }
  });

  // Admin: Update product price
  app.patch("/api/admin/products/:id/price", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const product = await storage.updateProductPrice(req.params.id, req.body.price);
      if (!product) {
        res.status(404).json({ success: false, message: "Product not found" });
        return;
      }

      res.json({ success: true, product });
    } catch (error) {
      console.error("Update price error:", error);
      res.status(500).json({ success: false, message: "Failed to update price" });
    }
  });

  // Admin: Update product info
  app.patch("/api/admin/products/:id", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const product = await storage.updateProductInfo(req.params.id, req.body);
      if (!product) {
        res.status(404).json({ success: false, message: "Product not found" });
        return;
      }

      // Clear product caches
      cache.delete('products');
      cache.delete('products-active');

      res.json({ success: true, product });
    } catch (error) {
      console.error("Update product error:", error);
      res.status(500).json({ success: false, message: "Failed to update product" });
    }
  });

  // Admin: Get admin dashboard stats
  app.get("/api/admin/stats", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const orders = await storage.getAllOrders();
      const contacts = await storage.getContactSubmissions();
      const users = Array.from((storage as any).users.values());
      
      res.json({
        success: true,
        stats: {
          totalUsers: users.length,
          totalOrders: orders.length,
          totalContacts: contacts.length,
          pendingOrders: orders.filter((o: any) => o.paymentStatus === 'pending').length,
        }
      });
    } catch (error) {
      console.error("Error fetching stats:", error);
      res.status(500).json({ success: false, message: "Failed to fetch stats" });
    }
  });

  // ADMIN: Create Product
  app.post("/api/admin/products", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      if (!payload) {
        res.status(401).json({ success: false, message: "Invalid token" });
        return;
      }

      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const product = await storage.createProduct(req.body);
      res.status(201).json({ success: true, product });
    } catch (error) {
      console.error("Create product error:", error);
      res.status(500).json({ success: false, message: "Failed to create product" });
    }
  });

  // ADMIN: Delete Products
  app.delete("/api/admin/products", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const { ids } = req.body;
      if (!ids || !Array.isArray(ids)) {
        res.status(400).json({ success: false, message: "Invalid product IDs" });
        return;
      }

      const deleted = await storage.deleteProducts(ids);
      res.json({ success: true, deleted });
    } catch (error) {
      console.error("Delete products error:", error);
      res.status(500).json({ success: false, message: "Failed to delete products" });
    }
  });

  // ADMIN: Get All Users
  app.get("/api/admin/users", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const users = await storage.getAllUsers();
      res.json({ success: true, users });
    } catch (error) {
      console.error("Get users error:", error);
      res.status(500).json({ success: false, message: "Failed to get users" });
    }
  });

  // ADMIN: Get User by ID
  app.get("/api/admin/users/:id", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const targetUser = await storage.getUserById(req.params.id);
      if (!targetUser) {
        res.status(404).json({ success: false, message: "User not found" });
        return;
      }

      res.json({ success: true, user: targetUser });
    } catch (error) {
      console.error("Get user error:", error);
      res.status(500).json({ success: false, message: "Failed to get user" });
    }
  });

  // ADMIN: Update User Role
  app.patch("/api/admin/users/:id/role", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || user.role !== "superadmin") {
        res.status(403).json({ success: false, message: "Only superadmin can change roles" });
        return;
      }

      const { role } = req.body;
      if (!["user", "moderator", "admin", "superadmin"].includes(role)) {
        res.status(400).json({ success: false, message: "Invalid role" });
        return;
      }

      const updatedUser = await storage.updateUserRole(req.params.id, role);
      if (!updatedUser) {
        res.status(404).json({ success: false, message: "User not found" });
        return;
      }

      res.json({ success: true, user: updatedUser });
    } catch (error) {
      console.error("Update role error:", error);
      res.status(500).json({ success: false, message: "Failed to update role" });
    }
  });

  // ADMIN: Block/Unblock User
  app.patch("/api/admin/users/:id/block", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const { blocked } = req.body;
      const updatedUser = await storage.blockUser(req.params.id, blocked);
      if (!updatedUser) {
        res.status(404).json({ success: false, message: "User not found" });
        return;
      }

      res.json({ success: true, user: updatedUser });
    } catch (error) {
      console.error("Block user error:", error);
      res.status(500).json({ success: false, message: "Failed to block user" });
    }
  });

  // ADMIN: Delete User
  app.delete("/api/admin/users/:id", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || user.role !== "superadmin") {
        res.status(403).json({ success: false, message: "Only superadmin can delete users" });
        return;
      }

      const deleted = await storage.deleteUser(req.params.id);
      if (!deleted) {
        res.status(404).json({ success: false, message: "User not found" });
        return;
      }

      res.json({ success: true, message: "User deleted" });
    } catch (error) {
      console.error("Delete user error:", error);
      res.status(500).json({ success: false, message: "Failed to delete user" });
    }
  });

  // ADMIN: Get User Orders
  app.get("/api/admin/users/:id/orders", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const orders = await storage.getUserOrders(req.params.id);
      res.json({ success: true, orders });
    } catch (error) {
      console.error("Get user orders error:", error);
      res.status(500).json({ success: false, message: "Failed to get orders" });
    }
  });

  // ADMIN: Create Admin User
  app.post("/api/admin/admins", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || user.role !== "superadmin") {
        res.status(403).json({ success: false, message: "Only superadmin can create admins" });
        return;
      }

      const { email, password, role, firstName, lastName } = req.body;
      
      if (!email || !password) {
        res.status(400).json({ success: false, message: "Email and password required" });
        return;
      }

      const existingUser = await storage.getUserByEmail(email);
      if (existingUser) {
        res.status(409).json({ success: false, message: "User already exists" });
        return;
      }

      const hashedPassword = await hashPassword(password);
      const newAdmin = await storage.createUser({
        email,
        password: hashedPassword,
        role: role || "admin",
        firstName: firstName || null,
        lastName: lastName || null,
      });

      res.status(201).json({ success: true, admin: newAdmin });
    } catch (error) {
      console.error("Create admin error:", error);
      res.status(500).json({ success: false, message: "Failed to create admin" });
    }
  });

  // ADMIN: Get Contact Submissions
  app.get("/api/admin/contacts", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const contacts = await storage.getContactSubmissions();
      res.json({ success: true, contacts });
    } catch (error) {
      console.error("Get contacts error:", error);
      res.status(500).json({ success: false, message: "Failed to get contacts" });
    }
  });

  // ADMIN: Delete Contact Submission
  app.delete("/api/admin/contacts/:id", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const deleted = await storage.deleteContactSubmission(req.params.id);
      if (!deleted) {
        res.status(404).json({ success: false, message: "Contact submission not found" });
        return;
      }

      res.json({ success: true, message: "Contact submission deleted" });
    } catch (error) {
      console.error("Delete contact error:", error);
      res.status(500).json({ success: false, message: "Failed to delete contact" });
    }
  });

  // ADMIN: Get Promo Codes
  app.get("/api/admin/promocodes", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const promoCodes = await storage.getPromoCodes();
      res.json({ success: true, promoCodes });
    } catch (error) {
      console.error("Get promo codes error:", error);
      res.status(500).json({ success: false, message: "Failed to get promo codes" });
    }
  });

  // ADMIN: Create Promo Code
  app.post("/api/admin/promocodes", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const promoCode = await storage.createPromoCode(req.body);
      res.status(201).json({ success: true, promoCode });
    } catch (error) {
      console.error("Create promo code error:", error);
      res.status(500).json({ success: false, message: "Failed to create promo code" });
    }
  });

  // ADMIN: Update Promo Code
  app.patch("/api/admin/promocodes/:id", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const promoCode = await storage.updatePromoCode(req.params.id, req.body);
      if (!promoCode) {
        res.status(404).json({ success: false, message: "Promo code not found" });
        return;
      }

      res.json({ success: true, promoCode });
    } catch (error) {
      console.error("Update promo code error:", error);
      res.status(500).json({ success: false, message: "Failed to update promo code" });
    }
  });

  // ADMIN: Delete Promo Code
  app.delete("/api/admin/promocodes/:id", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const deleted = await storage.deletePromoCode(req.params.id);
      if (!deleted) {
        res.status(404).json({ success: false, message: "Promo code not found" });
        return;
      }

      res.json({ success: true, message: "Promo code deleted" });
    } catch (error) {
      console.error("Delete promo code error:", error);
      res.status(500).json({ success: false, message: "Failed to delete promo code" });
    }
  });

  // ADMIN: Get Site Settings
  app.get("/api/admin/settings", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const settings = await storage.getSiteSettings();
      res.json({ success: true, settings });
    } catch (error) {
      console.error("Get settings error:", error);
      res.status(500).json({ success: false, message: "Failed to get settings" });
    }
  });

  // ADMIN: Update Site Setting
  app.put("/api/admin/settings/:key", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const { value, type, description } = req.body;
      const setting = await storage.setSiteSetting(req.params.key, value, type, description);
      res.json({ success: true, setting });
    } catch (error) {
      console.error("Update setting error:", error);
      res.status(500).json({ success: false, message: "Failed to update setting" });
    }
  });

  // USER: Change Password
  app.post("/api/auth/change-password", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user) {
        res.status(404).json({ success: false, message: "User not found" });
        return;
      }

      const { currentPassword, newPassword } = req.body;

      if (!currentPassword || !newPassword) {
        res.status(400).json({ success: false, message: "Current and new passwords required" });
        return;
      }

      const isValid = await verifyPassword(currentPassword, user.passwordHash || user.password);
      if (!isValid) {
        res.status(400).json({ success: false, message: "Current password is incorrect" });
        return;
      }

      if (newPassword.length < 8) {
        res.status(400).json({ success: false, message: "Password must be at least 8 characters" });
        return;
      }

      const hashedPassword = await hashPassword(newPassword);
      await storage.updateUser(user.id, { passwordHash: hashedPassword, password: hashedPassword });

      res.json({ success: true, message: "Password changed successfully" });
    } catch (error) {
      console.error("Change password error:", error);
      res.status(500).json({ success: false, message: "Failed to change password" });
    }
  });

  // USER: Mark Notification as Read
  app.patch("/api/notifications/:id/read", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      await storage.markNotificationAsRead(req.params.id);
      res.json({ success: true });
    } catch (error) {
      console.error("Mark notification as read error:", error);
      res.status(500).json({ success: false, message: "Failed to mark as read" });
    }
  });

  // ADMIN: Get product images
  app.get("/api/admin/products/:id/images", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const images = await storage.getProductImages(req.params.id);
      res.json({ success: true, images });
    } catch (error) {
      console.error("Get product images error:", error);
      res.status(500).json({ success: false, message: "Failed to get images" });
    }
  });

  // ADMIN: Add product image (accepts both base64 and URL)
  app.post("/api/admin/products/:id/images", async (req, res) => {
    try {
      console.log(`📸 [POST /api/admin/products/:id/images] Starting image upload for product: ${req.params.id}`);
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const { imageUrl, imageBase64 } = req.body;
      const imageData = imageBase64 || imageUrl;
      
      if (!imageData || typeof imageData !== 'string') {
        console.error(`❌ [POST /api/admin/products/:id/images] No image data provided`);
        res.status(400).json({ success: false, message: "Image data required" });
        return;
      }

      console.log(`📝 [POST /api/admin/products/:id/images] Image data length: ${imageData.length} chars`);

      // Validate base64 size (max 5MB)
      if (imageData.startsWith('data:image')) {
        const base64Size = calculateBase64Size(imageData);
        console.log(`📦 [POST /api/admin/products/:id/images] Base64 size: ${(base64Size / 1024 / 1024).toFixed(2)}MB`);
        if (base64Size > 5 * 1024 * 1024) {
          res.status(400).json({ success: false, message: "Image too large (max 5MB)" });
          return;
        }
      }

      console.log(`🔄 [POST /api/admin/products/:id/images] Calling storage.addProductImage()`);
      const product = await storage.addProductImage(req.params.id, imageData);
      if (!product) {
        console.error(`❌ [POST /api/admin/products/:id/images] Product not found`);
        res.status(404).json({ success: false, message: "Product not found" });
        return;
      }

      console.log(`🗑️ [POST /api/admin/products/:id/images] Clearing caches`);
      // Clear product caches
      cache.delete('products');
      cache.delete('products-active');
      console.log(`✅ [POST /api/admin/products/:id/images] Caches cleared`);

      console.log(`✨ [POST /api/admin/products/:id/images] SUCCESS - returning product with ${product.images ? product.images.length : 0} images`);
      res.json({ success: true, product });
    } catch (error) {
      console.error("❌ Add product image error:", error);
      res.status(500).json({ success: false, message: "Failed to add image" });
    }
  });

  // ADMIN: Remove product image
  app.delete("/api/admin/products/:id/images", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const { imageUrl, imageData } = req.body;
      const dataToRemove = imageData || imageUrl;
      
      if (!dataToRemove || typeof dataToRemove !== 'string') {
        res.status(400).json({ success: false, message: "Image data required" });
        return;
      }

      const product = await storage.removeProductImage(req.params.id, dataToRemove);
      if (!product) {
        res.status(404).json({ success: false, message: "Product not found" });
        return;
      }

      // Clear product caches
      cache.delete('products');
      cache.delete('products-active');

      res.json({ success: true, product });
    } catch (error) {
      console.error("Remove product image error:", error);
      res.status(500).json({ success: false, message: "Failed to remove image" });
    }
  });

  // ADMIN: Send notification to user
  app.post("/api/admin/notifications/send", async (req, res) => {
    try {
      const token = req.headers.authorization?.replace("Bearer ", "");
      if (!token) {
        res.status(401).json({ success: false, message: "Not authenticated" });
        return;
      }

      const payload = verifyAccessToken(token);
      const user = await storage.getUserById(payload.userId);
      if (!user || (user.role !== "admin" && user.role !== "superadmin")) {
        res.status(403).json({ success: false, message: "Not authorized" });
        return;
      }

      const { userId, title, message, type = "info", link } = req.body;
      
      if (!title || !message) {
        res.status(400).json({ success: false, message: "Title and message required" });
        return;
      }

      if (userId) {
        // Send to specific user
        const targetUser = await storage.getUserById(userId);
        if (!targetUser) {
          res.status(404).json({ success: false, message: "User not found" });
          return;
        }

        const notification = await storage.sendNotificationToUser(userId, {
          title: sanitizeInput(title, 200),
          message: sanitizeInput(message, 1000),
          type: sanitizeInput(type, 50),
          link: link ? sanitizeInput(link, 500) : null,
        });

        // Send email notification
        if (targetUser.email) {
          const emailHtml = `
            <div style="font-family: Arial, sans-serif; color: #333;">
              <h2 style="color: #1a1a1a; border-bottom: 2px solid #4CAF50; padding-bottom: 10px;">${escapeHtml(title)}</h2>
              <p style="margin: 15px 0; line-height: 1.6;">${escapeHtml(message).replace(/\n/g, '<br>')}</p>
              ${link ? `<p style="margin-top: 20px;"><a href="${escapeHtml(link)}" style="color: #4CAF50; text-decoration: none;">Перейти →</a></p>` : ''}
            </div>
          `;
          sendEmail(targetUser.email, title, emailHtml).catch(err => {
            console.error("Failed to send notification email:", err);
          });
        }

        res.json({ success: true, notification });
      } else {
        // Send to all users
        const notifications = await storage.sendNotificationToAllUsers({
          title: sanitizeInput(title, 200),
          message: sanitizeInput(message, 1000),
          type: sanitizeInput(type, 50),
          link: link ? sanitizeInput(link, 500) : null,
        });

        // Send email to all users
        const allUsers = await storage.getAllUsers();
        for (const targetUser of allUsers) {
          if (targetUser.email) {
            const emailHtml = `
              <div style="font-family: Arial, sans-serif; color: #333;">
                <h2 style="color: #1a1a1a; border-bottom: 2px solid #4CAF50; padding-bottom: 10px;">${escapeHtml(title)}</h2>
                <p style="margin: 15px 0; line-height: 1.6;">${escapeHtml(message).replace(/\n/g, '<br>')}</p>
                ${link ? `<p style="margin-top: 20px;"><a href="${escapeHtml(link)}" style="color: #4CAF50; text-decoration: none;">Перейти →</a></p>` : ''}
              </div>
            `;
            sendEmail(targetUser.email, title, emailHtml).catch(err => {
              console.error("Failed to send notification email:", err);
            });
          }
        }

        res.json({ success: true, count: notifications.length });
      }
    } catch (error) {
      console.error("Send notification error:", error);
      res.status(500).json({ success: false, message: "Failed to send notification" });
    }
  });

  // Register auth routes
  const httpServer = createServer(app);

  return httpServer;
}
